[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  LANG = "en_US.UTF-8"
  LC_ALL = "en_US.UTF-8"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
